import type { Metadata } from "next"
import "./globals.css"
import { montserrat } from '@/fonts'
import Nav from "@/components/nav/Nav"  
import Footer from '@/components/footer/Footer';
import { Toaster } from '@/components/ui/sonner'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`dark scroll-smooth
      ${montserrat.className} ${montserrat.variable}
      `}
    >
      <body className="antialiased bg-gs-bg h-screen font-sans">
        <header>
         <Nav />
        </header>
        {children}
        <Toaster position="bottom-right" />
        <Footer/>
      </body>
    </html>
  )
}