import type { Metadata } from "next"
import "./globals.css"
import { oldFenris, quattrocento, montserrat } from "@/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`
        ${oldFenris.variable}
        ${quattrocento.variable}
        ${montserrat.variable}
      `}
    >
      <body className="antialiased bg-stone-950 h-screen">
        {children}
      </body>
    </html>
  )
}