import type { Metadata } from "next"
import "./globals.css"
import { montserrat } from '@/fonts'
import Nav from "@/components/nav/Nav"  

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`dark
      ${montserrat.className} ${montserrat.variable}
      `}
    >
      <body className="antialiased bg-stone-950 h-screen font-sans">
        <header>
         <Nav />
        </header>
        {children}
      </body>
    </html>
  )
}